# Use this script to generate a prompt for an LLM to review the JAGS code for an mcp_example()
# I ran these by Geminin 3.1 Pro in 2026-08-01 with no errors.

build_llm_prompt = function(fit) {
    jags_data = mcp:::get_jags_data(
        data = fit$data,
        family = fit$family,
        segments = fit$.internal$model_tables$segments,
        predictors = fit$.internal$model_tables$predictors,
        group_effects = fit$.internal$model_tables$group_effects,
        jags_code = fit$jags_code
    )
    attributes(jags_data$response) = NULL # Remove simulated values

    paste0(
        "You are an expert in Bayesian statistics and JAGS modeling. Please review the following JAGS code generated by the `mcp` R package to verify whether it accurately represents the specified model.\n\n",
        "## 1. Model Summary\n",
        paste(capture.output(summary(fit)), collapse = "\n"), "\n\n",
        "## 2. Generated JAGS Code (`fit$jags_code`)\n```jags\n",
        fit$jags_code, "\n```\n\n",
        "## 3. JAGS Input Data (`jags_data` structure)\n```r\n",
        paste(capture.output(str(jags_data)), collapse = "\n"), "\n```\n\n",
        "## Task\n",
        "1. Check if the mathematical formulation in `jags_code` accurately matches the model structure and priors shown in the summary.\n",
        "2. Verify matrix/vector indexing against the structures in `jags_data`.\n",
        "3. Flag any discrepancies, indexing errors, or unintended behaviors."
    )
}

devtools::load_all()
fit = mcp_example("multiple")
prompt = build_llm_prompt(fit)
cat(prompt)
