# ABOUT: These functions call the JAGS sampler and set up inputs in a way
# that is appropriate for that, including data (get_jags_data()).
# ------------------------------------------------------------------------


#' Run parallel MCMC sampling using JAGS.
#'
#'
#' @aliases run_jags
#' @keywords internal
#' @noRd
#' @inheritParams mcp
#' @inheritParams rjags::jags.model
#' @inheritParams rjags::coda.samples
#' @param jags_code A string. JAGS model, usually returned by `get_jags_code()`.
#' @param pars Character vector of parameters to save/monitor.
#' @return `mcmc.list``
#' @encoding UTF-8
#' @author Jonas Kristoffer Lindeløv \email{jonas@@lindeloev.dk}
run_jags = function(data,
                    jags_code,
                    jags_data,
                    pars,
                    sample,
                    n.chains,
                    n.iter,
                    n.adapt,
                    inits,
                    seed,
                    quiet
) {

  # Define the sampling function in this environment.
  # Can be used sequentially or in parallel.
  do_sampling = function(inits, n.chains) {
    sample_jags = function() {
      # Compile model
      jags_connection = textConnection(jags_code)
      on.exit(close(jags_connection), add = TRUE)
      jm = rjags::jags.model(
        file = jags_connection,
        data = jags_data,
        inits = inits,
        n.chains = n.chains,
        n.adapt = n.adapt,
        quiet = quiet
      )

      # Sample and return
      rjags::coda.samples(
        model = jm,
        variable.names = pars,
        n.iter = n.iter,
        quiet = quiet
      )
    }

    # rjags still prints some adaptation notices with quiet = TRUE.
    if (quiet) {
      draws = NULL
      capture.output({ draws = sample_jags() })
    } else {
      draws = sample_jags()
    }
    draws
  }

  # Use JAGS directly under a sequential future plan. This compiles the model
  # only once for all chains and preserves JAGS's progress output.
  n_workers = future::nbrOfWorkers()
  timer = proc.time()
  if (n_workers == 1) {
    inits = get_jags_inits(inits, seed, n.chains, sample)
    draws = do_sampling(
      inits = inits,
      n.chains = n.chains
    )
  } else {
    # Submit one chain per future. The user's future plan controls the backend.
    if (!quiet)
      message("Parallel sampling in progress...")
    if (is.null(seed))
      seed = sample.int(.Machine$integer.max - 2 * n.chains, 1)
    inits = get_jags_inits(inits, seed, n.chains, sample)
    draws = future.apply::future_lapply(
      inits,
      n.chains = 1,
      FUN = do_sampling,
      future.seed = TRUE
    )

    # Get result as mcmc.list
    draws = unlist(draws, recursive = FALSE)
    class(draws) = "mcmc.list"
  }

  # Sampling finished
  passed = proc.time() - timer
  if (!quiet)
    message("Finished sampling in ", round(passed["elapsed"], 1), " seconds\n")

  draws
}


#' Add deterministic JAGS RNG initial values
#'
#' @keywords internal
#' @noRd
#' @param inits Initial values passed to `mcp()`.
#' @param seed A positive integer or `NULL`.
#' @param n.chains Number of chains.
#' @param sample One of `"post"` or `"prior"`.
#' @return Initial values in list-of-lists form when `seed` is supplied.
get_jags_inits = function(inits, seed, n.chains, sample) {
  if (is.null(seed))
    return(inits)

  if (length(inits) > 0 && all(vapply(inits, is.list, logical(1))))
    stop(
      "When `seed` is supplied, `inits` must be a single named list ",
      "shared by all chains, not a list of chain-specific lists."
    )

  if (is.null(inits))
    inits = list()
  inits[c(".RNG.name", ".RNG.seed", ".RNG.state")] = NULL

  rng_seed = seq_len(n.chains)
  if (sample == "prior")
    rng_seed = rng_seed + n.chains
  rng_seed = as.integer(
    ((as.double(seed) - 1 + rng_seed - 1) %% .Machine$integer.max) + 1
  )

  lapply(
    rng_seed,
    function(seed) {
      c(inits, list(
        .RNG.name = "base::Wichmann-Hill",
        .RNG.seed = seed
      ))
    }
  )
}


#' Check user data names against generated JAGS nodes
#'
#' @keywords internal
#' @noRd
#' @param data_names Names of user-data nodes passed to JAGS.
#' @param family An `mcpfamily` object.
#' @param segments A segment table returned by `get_segment_tables()`.
#' @param predictors Returned by `get_predictors()`.
#' @param group_effects Returned by `get_group_effects()`.
#' @param jags_code Generated or custom JAGS code.
#' @param generated Whether `jags_code` was generated by mcp.
assert_jags_namespace = function(data_names, family, segments, predictors,
                                  group_effects, jags_code, generated = TRUE) {
  group_cols = unique(stats::na.omit(group_effects$group_col))
  dpars = family$dpar_specs$dpar

  # Public parameters and fixed change-point boundary nodes share one namespace.
  parameter_names = stats::na.omit(c(
    paste0("cp_", 0:nrow(segments)), "cp_betas",
    predictors$code_name,
    group_effects$name, group_effects$sd_name
  ))
  inverse_candidates = paste0(c(predictors$code_name, group_effects$name), "_inverse")
  inverse_names = if (is.null(jags_code)) character() else
    inverse_candidates[vapply(
      inverse_candidates, grepl, logical(1), x = jags_code, fixed = TRUE
    )]

  # Data helpers are always present; model helpers occur only in generated code.
  helper_names = unique(c(
    "rhs_matrix_", "series_id_", "cp_order_", "response_observed_",
    "likelihood_weight_", "likelihood_zero_",
    paste0("n_unique_", group_cols), paste0(group_cols, "_"),
    names(attr(jags_code, "jags_constants")),
    if (generated) c(
      "i_", "garma_boundary_", "garma_y_", "garma_link_y_",
      "resid_abs_", "resid_ma_", "resid_garma_", "nb_prob_",
      paste0("x_local_", seq_len(nrow(segments)), "_"),
      paste0("link_", dpars, "_"), paste0(dpars, "_"), inverse_names
    )
  ))

  # Catch parameter-to-parameter and parameter-to-helper collisions before priors.
  duplicate_parameters = unique(parameter_names[
    duplicated(parameter_names) | duplicated(parameter_names, fromLast = TRUE)
  ])
  parameter_helpers = intersect(parameter_names, helper_names)
  generated_collisions = unique(c(duplicate_parameters, parameter_helpers))
  if (length(generated_collisions) > 0)
    stop(
      "Generated parameter name(s) collide in the JAGS namespace: ",
      and_collapse(paste0("'", generated_collisions, "'")),
      ". Rename the corresponding predictor column."
    )

  # Finally, ensure user data cannot overwrite any generated JAGS node.
  collisions = intersect(data_names, c(parameter_names, helper_names))
  reserved_prefix = grep("^\\.?mcp_", data_names, value = TRUE)
  bad = unique(c(collisions, reserved_prefix))
  if (length(bad) > 0)
    stop(
      "Data column name(s) collide with mcp's generated JAGS namespace: ",
      and_collapse(paste0("'", bad, "'")), ". Rename them before fitting."
    )
  invisible(TRUE)
}


#' Adds helper variables for use in `run_jags`
#'
#' Returns the relevant data columns as a list and add elements with unique
#' grouping-factor levels.
#'
#' @aliases get_jags_data
#' @keywords internal
#' @noRd
#' @inheritParams run_jags
#' @param data A tibble
#' @param segments A segment table returned by `get_segment_tables()`.
#' @param predictors Returned by `get_predictors()`.
#' @param group_effects Returned by `get_group_effects()`.
get_jags_data = function(data, family, segments, predictors, group_effects, jags_code,
                          series = NULL, generated = TRUE) {
  group_cols = unique(stats::na.omit(group_effects$group_col))

  # Start with "raw" data
  aux_columns = get_family_aux_columns(family, segments)
  cols_data = unique(stats::na.omit(c(segments$y, segments$x, unname(aux_columns))))
  assert_jags_namespace(
    unique(c(group_cols, cols_data, series)), family, segments, predictors,
    group_effects, jags_code, generated
  )
  jags_data = as.list(data[, c(group_cols, cols_data)])

  if (!is.null(series))
    jags_data$series_id_ = as.integer(factor(data[[series]], levels = unique(data[[series]])))

  for (col in group_cols) {
    # Add metadata for the grouping-factor levels.
    tmp = paste0("n_unique_", col)
    jags_data[[tmp]] = length(unique(data[, col]))

    # Make grouping columns numeric in order of appearance.
    # They will be recovered using the recover_levels()
    jags_data[[col]] = as.numeric(factor(jags_data[[col]], levels = unique(jags_data[[col]])))
  }

  cp_group_effects = group_effects[group_effects$part == "cp", , drop = FALSE]
  if (nrow(cp_group_effects) > 0 && nrow(segments) > 2 &&
      grepl("cp_order_", jags_code, fixed = TRUE)) {
    n_group = length(unique(data[[cp_group_effects$group_col[1]]]))
    jags_data$cp_order_ = matrix(1, nrow = n_group, ncol = nrow(segments) - 2L)
  }

  # Predictor design matrix. Keep the JAGS data name for custom-code compatibility.
  jags_data$rhs_matrix_ = get_predictor_matrix(predictors, group_effects)

  # Add named data constants for change point prior bounds (see jagsify_constants())
  jags_constants = attr(jags_code, "jags_constants")
  if (!is.null(jags_constants))
    jags_data[names(jags_constants)] = jags_constants

  # Compatibility for custom JAGS code written with the released data
  # constants. Generated code and newly resolved priors no longer need these.
  context = prior_context(data, segments)
  jags_data = add_legacy_prior_jags_data(jags_data, jags_code, context)

  if (generated && grepl("response_observed_", jags_code, fixed = TRUE))
    jags_data$response_observed_ = as.integer(!is.na(data[[segments$y[1]]]))
  if (generated && grepl("likelihood_zero_", jags_code, fixed = TRUE))
    jags_data$likelihood_zero_ = numeric(nrow(data))

  # Return
  jags_data
}


#' Recover the levels of group-level effects in mcmc.list
#'
#' JAGS uses 1, 2, 3, ... for indexing group-level effects.
#' This function adds back the original levels, whether numeric or string
#'
#' @aliases recover_levels
#' @keywords internal
#' @noRd
#' @param draws An mcmc.list with group-level columns starting in `mcmc_col`.
#' @param data A tibble or data.frame
#' @param group_effects Returned by `get_group_effects()`.
recover_levels = function(draws, data, group_effects) {
  for (i in seq_len(nrow(group_effects))) {
    effect = group_effects[i, ]
    # Get vectors of old ("from") and replacement column names in draws
    from = colnames(draws[[1]])[stringr::str_starts(colnames(draws[[1]]), paste0(effect$name, '\\['))]
    to = sprintf(paste0(effect$name, '[%s]'), unique(data[, effect$group_col]))

    # Recode column names on each list (chain) using lapply
    names(to) = from
    draws = lapply(draws, function(x) {
      colnames(x) = dplyr::recode(colnames(x), !!!to)
      x
    })
  }

  draws
}
